swagger: "2.0"
schemes:
  - http
host: 'localhost:3000'
basePath: /
info:
  version: '1.0'
  title: skus_api_document_embedded
  description: Administa o catalógo e estoque de produtos de um e-commerce
  contact:
    name: Suporte
    email: zogbivitor@gmail.com.br
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: products
  - name: skus
paths:
  
  '/products':
    post:
      tags:
        - products
      summary: Cria um produto
      description: Cria um novo produto
      operationId: createProduct
      parameters:
        - in: body
          name: product
          required: true
          schema:
            $ref: '#/definitions/products'
      responses:
        '201':
          description: ok
        '404':
          description: Produto não criado
        '422':
          description: Erro com os dados do produto
        '500':
          description: Falha ao criar o produto        
    get:
      tags:
        - products
      summary: Lista os produtos com paginação
      description: Lista os produtos com suas skus em formato paginado
      operationId: listProducts
      parameters:
        - in: header
          name: page
          type: string
      responses:
        '200':
          description: Produto(s) encontrado(s)
          schema:
            $ref: '#/definitions/products'
        '206':
          description: Nenhum produto encontrado
        '500':
          description: Falha ao carregar os produtos
  
  '/products/{id}':
    get:
      tags:
        - products
      summary: Encontra um produto através de sua Id
      description: Retorna um produto com suas skus
      operationId: findProductById
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: query
          name: products
          type: string
      responses:
        '200':
          description: Produto encontrado
          schema:
            $ref: '#/definitions/products'
        '404':
          description: Produto não encontrado
        '422':
          description: Erro com os dados produto
        '500':
          description: Falha ao encontrar o produto  
    put:
      tags:
        - products
      summary: Atualiza um produto
      description: Atualiza os dados base de um produto com base na sua id
      operationId: updateProduct
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: products
          required: true
          schema:
            $ref: '#/definitions/products'
        - in: query
          name: products
          type: string
      responses:
        '201':
          description: Produto atualizado
          schema:
            $ref: '#/definitions/products'
        '404' :
          description: Produto não atualizado
        '422':
          description: errors
        '500':
          description: Não foi possível alterar o produto
    delete:
      tags:
        - products
      summary: Exclui o produto
      description: Exclusão de um produto através do Id
      operationId: deleteProduct
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: query
          name: products
          type: string
      responses:
        '204':
          description: Ok
        '404':
          description: Produto não apagado
        '422':
          description: errors
        '500':
          description: Falha ao apagar o produto
  
  '/skus':
    
    get:
      tags:
        - skus
      summary: Lista as skus com paginação
      description: Lista as skus em formato paginado
      operationId: listSkus
      parameters:
        - in: header
          name: page
          type: string
      responses:
        '200':
          description: Produto(s) encontrado(s)
          schema:
            $ref: '#/definitions/products'
        '206':
          description: Nenhum produto encontrado
        '500':
          description: Falha ao carregar os produtos
          
  '/skus/{id}':
  
    post:
      tags:
        - skus
      summary: Cria uma sku
      description: Cria uma novao sku
      operationId: createSku
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: sku
          required: true
          schema:
            $ref: '#/definitions/products'
      responses:
        '201':
          description: ok
        '404':
          description: Sku não criada
        '422':
          description: Erro com os dados da sku
        '500':
          description: Falha ao criar a sku
  
    get:
      tags:
        - skus
      summary: Encontra uma sku através de sua Id
      description: Retorna uma sku
      operationId: findSkuById
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: query
          name: products
          type: string
      responses:
        '200':
          description: Sku encontrada
          schema:
            $ref: '#/definitions/products'
        '404':
          description: Sku não encontrada
        '422':
          description: Erro com os dados da sku
        '500':
          description: Falha ao encontrar a sku  
    put:
      tags:
        - skus
      summary: Atualiza uma sku
      description: Atualiza os dados de uma sku com base na sua id
      operationId: updateSku
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: body
          name: sku
          required: true
          schema:
            $ref: '#/definitions/products'
        - in: query
          name: sku
          type: string
      responses:
        '201':
          description: Sku atualizada
          schema:
            $ref: '#/definitions/products'
        '404' :
          description: Sku não atualizada
        '422':
          description: errors
        '500':
          description: Não foi possível alterar a sku
    delete:
      tags:
        - skus
      summary: Exclui a sku
      description: Exclusão de uma sku através do Id
      operationId: deleteSku
      parameters:
        - in: path
          name: id
          type: string
          required: true
        - in: query
          name: sku
          type: string
      responses:
        '204':
          description: Ok
        '404':
          description: Sku não apagada
        '422':
          description: errors
        '500':
          description: Falha ao apagar o sku
          
definitions:
  
  products:
    type: object
    properties:
      _id:
        type: string
        example: 5d9276e9972aa819ecfc8684
      name:
        type: string
        format: utf-8
        example: Camisa
      description:
        type: string
        example: "Item de vestúario"
      active:
        type: boolean
        default: false
      sku:
        type: array
        items:
          type: object
          properties:
            color:
              type: string
              format: utf-8
              example: rose
            size:
              type: string
              format: utf-8
              example: GG
            price:
              type: number
              format: double
              example: 99.99
            stockLevel:
              type: number
              format: integer
              example: 10
            active:
              type: boolean